const listOfFeatures = ["Fast", "Powerful", "Secure", "Private", "Unlimited", "Synced", "Reliable"];
const drawerListTitles= [account,friends,notification,datastorage,help];
const appname = "Quick Chats",

    account = "Account",
    friends = "Friends",
    notification = "Notification",
    datastorage = "Data and Storage",
    help = "Help",
    chats = "Chats",
    status = "Status",
    camera = "Camera",
    invite = "Invite a friend",
    logout = "Logout",
    settings = "Settings",
    username = "Username",
    poweredby = "Designed & Developed by Aakash",
    cont = "Start Messaging",
    ConnectingLives ="connecting lives...",
    continuetext = "Continue",
    otp = "We will send SMS with a confirmation code to your Phone Number",
    letsconnect = "Let's connect",
    slogan = "join the\nrevolution\ntoday";
